### ISSUE TITLE
Needs older version of TextformatterHannaCode?

### ISSUE THREAD

**Issue by mattgs** [BitPoet/HannaCodeDialogTiny#1]
With the latest version of the HannaCode module (0.3.2 Stable at this moment in time) it's throwing the following error:

`Method TextformatterHannaCode::extractDefaultCodeAttrs does not exist or is not callable in this context`

Method `extractDefaultCodeAttrs` has been removed from the HannaCode module some time ago.

**Comment by mattgs** [comment]
This seems to be a quick fix:

HannaCodeDialogTiny.module
Line 140: $h = $hanna->hannaCodes()->get($name);
Line 141: foreach($h->attrs as $attr_name => $attr_value) {

**Comment by BitPoet** [comment]
Thanks for reporting this. I wasn't aware that I was working with an old release of HannaCode. I added a version switch so it works with the old and new TextformatterHannaCode API.
